package com.xu.drools;

/**
*  AB: 两组
   组1 >=3 人
   组2 >=4 人
*
*/

import com.xu.drools.rule.arrange.Employee;

function String hello(String name) {
    return "Hello "+name+"!";
}


rule "g1-01"
	when
        $p : Employee(group=="g1" ,(order%3) == 1);
    then
        $p.setArrangeJson("{{W:1,S:0}," +
          "{W:2,S:A }," +
          "{W:3,S:A }," +
          "{W:4,S:A }," +
          "{W:5,S:A }," +
          "{W:6,S:A }," +
          "{W:7,S:0 }}");
        //update($p)
        //$p.setArrangeJson(hello1(1));
        //System.out.println(hello1($p.getOrder()));
        System.out.println(hello($p.getName()));
end
rule "g1-02"
	when
        $p : Employee(group=="g1" ,(order%3) == 2);
    then
        $p.setArrangeJson("{{W:1,S:A}," +
          "{W:2,S:0 }," +
          "{W:3,S:A }," +
          "{W:4,S:A }," +
          "{W:5,S:A }," +
          "{W:6,S:0 }," +
          "{W:7,S:A }}");
        //update($p)
        //$p.setArrangeJson(hello2(2));
        //System.out.println(hello2($p.getOrder()));
        System.out.println("hello, "+$p.getName());
end

rule "g1-03"
	when
        $p : Employee(group=="g1" ,(order%3) == 0);
    then
        $p.setArrangeJson("{{W:1,S:A}," +
          "{W:2,S:A }," +
          "{W:3,S:0 }," +
          "{W:4,S:A }," +
          "{W:5,S:0 }," +
          "{W:6,S:A }," +
          "{W:7,S:A }}");
        //update($p)
        //System.out.println(hello3($p.getOrder()));
        //$p.setArrangeJson(hello3(3));
        System.out.println("hello, "+$p.getName());
end


rule "g2-01"
	when
        $p : Employee(group=="g2" ,(order%4) == 1);
    then
        $p.setArrangeJson("{{W:1,S:0}," +
          "{W:2,S:0 }," +
          "{W:3,S:A }," +
          "{W:4,S:A }," +
          "{W:5,S:A }," +
          "{W:6,S:A }," +
          "{W:7,S:A }}");
        //update($p)
        //System.out.println(hello4($p.getOrder()));
        //$p.setArrangeJson(hello4(4));
        System.out.println("hello, "+$p.getName());
end

rule "g2-02"
	when
        $p : Employee(group=="g2" , (order%4) == 2);
    then
        $p.setArrangeJson("{{W:1,S:A}," +
          "{W:2,S:A }," +
          "{W:3,S:0 }," +
          "{W:4,S:0 }," +
          "{W:5,S:A }," +
          "{W:6,S:A }," +
          "{W:7,S:A }}");
        //update($p)
        //System.out.println(hello4($p.getOrder()));
        //$p.setArrangeJson(hello4(4));
        System.out.println("hello, "+$p.getName());
end

rule "g2-03"
	when
        $p : Employee(group=="g2" , (order%4) == 3);
    then
        $p.setArrangeJson("{{W:1,S:A}," +
          "{W:2,S:A }," +
          "{W:3,S:A }," +
          "{W:4,S:A }," +
          "{W:5,S:0 }," +
          "{W:6,S:0 }," +
          "{W:7,S:A }}");
        //update($p)
        //System.out.println(hello4($p.getOrder()));
        //$p.setArrangeJson(hello4(4));
        System.out.println("hello, "+$p.getName());
end

rule "g2-04"
	when
        $p : Employee(group=="g2" , (order%4) == 0);
    then
        $p.setArrangeJson("{{W:1,S:0}," +
          "{W:2,S:A }," +
          "{W:3,S:A }," +
          "{W:4,S:A }," +
          "{W:5,S:A }," +
          "{W:6,S:A }," +
          "{W:7,S:0 }}");
        //update($p)
        //System.out.println(hello4($p.getOrder()));
        //$p.setArrangeJson(hello4(4));
        System.out.println("hello, "+$p.getName());
end




query "Employee"
    employee : Employee( name == "lisi" )
end