package com.xu.drools;

/**
*  RB: 4人以上
*
*/


import com.xu.drools.rule.arrange.Employee;

function String hello(String name) {
    return "Hello "+name+"!";
}

function String  hello1(int  order) {
    String str = "{";
    int i = 1;
    for(; i<=31; i++){
       if(i%4==1){
          str +="d"+i+":B,";
       }else if(i%4==2){
          str +="d"+i+":A,";
       }else if(i%4==3){
          str +="d"+i+":C,";
       }else if(i%4==0){
          str +="d"+i+":0,";
       }
    }
    str = str.substring(0,str.length() - 1);
    return str+"}";
}

function String  hello2(int  order) {
    String str = "{";
    int i = 1;
    for(; i<=31; i++){
       if(i%4==1){
          str +="d"+i+":A,";
       }else if(i%4==2){
          str +="d"+i+":C,";
       }else if(i%4==3){
          str +="d"+i+":0,";
       }else if(i%4==0){
          str +="d"+i+":B,";
       }
    }
    str = str.substring(0,str.length() - 1);
    return str+"}";
}

function String  hello3(int  order) {
    String str = "{";
    int i = 1;
    for(; i<=31; i++){
       if(i%4==1){
          str +="d"+i+":C,";
       }else if(i%4==2){
          str +="d"+i+":0,";
       }else if(i%4==3){
          str +="d"+i+":B,";
       }else if(i%4==0){
          str +="d"+i+":A,";
       }
    }
    str = str.substring(0,str.length() - 1);
    return str+"}";
}

function String  hello4(int  order) {
    String str = "{";
    int i = 1;
    for(; i<=31; i++){
       if(i%4==1){
          str +="d"+i+":0,";
       }else if(i%4==2){
          str +="d"+i+":B,";
       }else if(i%4==3){
          str +="d"+i+":A,";
       }else if(i%4==0){
          str +="d"+i+":C,";
       }
    }
    str = str.substring(0,str.length() - 1);
    return str+"}";
}




rule "g1-01"
	when
        $p : Employee((order%4) == 1);
    then
//        $p.setArrangeJson("{{w:1,s:A}," +
//          "{w:2,S:B }," +
//          "{w:3,S:C }," +
//          "{w:4,S:0 }," +
//          "{w:5,S:A }," +
//          "{w:6,S:B }," +
//          "{s:7,w:C }}");
        //update($p)
        $p.setArrangeJson(hello1(1));
        //System.out.println(hello1($p.getOrder()));
        System.out.println(hello($p.getName()));
end
rule "g1-02"
	when
        $p : Employee((order%4) == 2);
    then
//        $p.setArrangeJson("{{w:1,s:B}," +
//          "{w:2,S:C }," +
//          "{w:3,S:0 }," +
//          "{w:4,S:A }," +
//          "{w:5,S:B }," +
//          "{w:6,S:C }," +
//          "{s:7,w:0 }}");
        //update($p)
        $p.setArrangeJson(hello2(2));
        //System.out.println(hello2($p.getOrder()));
        System.out.println("hello, "+$p.getName());
end

rule "g1-03"
	when
        $p : Employee( (order%4) == 3);
    then
//        $p.setArrangeJson("{{w:1,s:C}," +
//          "{w:2,S:0 }," +
//          "{w:3,S:A }," +
//          "{w:4,S:B }," +
//          "{w:5,S:C }," +
//          "{w:6,S:0 }," +
//          "{s:7,w:A }}");
        //update($p)
        //System.out.println(hello3($p.getOrder()));
        $p.setArrangeJson(hello3(3));
        System.out.println("hello, "+$p.getName());
end
rule "g1-04"
	when
        $p : Employee( (order%4) == 0);
    then
//        $p.setArrangeJson("{{w:1,s:0}," +
//          "{w:2,S:A }," +
//          "{w:3,S:B }," +
//          "{w:4,S:C }," +
//          "{w:5,S:0 }," +
//          "{w:6,S:A }," +
//          "{s:7,w:B }}");
        //update($p)
        //System.out.println(hello4($p.getOrder()));
        $p.setArrangeJson(hello4(4));
        System.out.println("hello, "+$p.getName());
end





query "Employee"
    employee : Employee( name == "lisi" )
end